baseURL = 'https://davepereira.co.uk/'
languageCode = 'en-GB'
title = 'Dave Pereira'
theme = 'blist'
metaDataFormat = "yaml"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2025 - Dave Pereira · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

  #  [params.homepage.social]
  # Global params common for both languages
   # title = "Follow me"
   # description = "Alittle about me"

   # [[params.homepage.social.icons]]
   #   website = "x"
   #   url = "https://x.com/"
   # [[params.homepage.social.icons]]
  #    website = "linkedin"
   #   url = "https://linkedin.com/in/"
 #   [[params.homepage.social.icons]]
   #   website = "xing"
   #   url = "https://www.xing.com/profile/"
 #   [[params.homepage.social.icons]]
   #   website = "telegram"
  #    url = "https://t.me/"
 #   [[params.homepage.social.icons]]
  #    website = "github"
  #    url = "https://github.com/"
  #  [[params.homepage.social.icons]]
  #    website = "buymeacoffee"
  #    url = "https://www.buymeacoffee.com/"
  #  [[params.homepage.social.icons]]
  #    website = "medium"
 #     url = "https://medium.com/"
  #  [[params.homepage.social.icons]]
  #    website = "reddit"
  #    url = "https://reddit.com/"
  #  [[params.homepage.social.icons]]
  #    website = "dribbble"
  #    url = "https://dribbble.com/"
  #  [[params.homepage.social.icons]]
   #   website = "stackoverflow"
   #   url = "https://stackoverflow.com/"
 #   [[params.homepage.social.icons]]
   #   website = "xda"
   #   url = "https://forum.xda-developers.com/"
   # [[params.homepage.social.icons]]
   #   website = "tiktok"
   #   url = "https://tiktok.com"
   # [[params.homepage.social.icons]]
   #   website = "googlescholar"
   #   url = "https://scholar.google.com/"
  #  [[params.homepage.social.icons]]
  #    website = "mastodon"
  #    url = "https://joinmastodon.org"
  #  [[params.homepage.social.icons]]
  #    website = "youtube"
 #     url = "https://youtube.com"
  #  [[params.homepage.social.icons]]
  #    website = "instagram"
  #    url = "https://instagram.com"
  #  [[params.homepage.social.icons]]
  #    website = "facebook"
  #    url = "https://facebook.com"
  #  [[params.homepage.social.icons]]
   #   website = "behance"
  #   url = "https://behance.net"

[[menu.main]]
  name = "About"
  url = "/about"

[outputs]
  home = ["HTML"]

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content"
    weight = 1
    languageName = "English"

    [languages.en.params]
      introTitle = "Hey! I'm Dave Pereira"
      introSubtitle = "Highly experienced digital marketing professional"
      introPhoto = "/picture.jpg"
      logo = "/blist-logo.png"

    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Portfolio"
        url = "portfolio/portfolio1"
        weight = 2
